### ISSUE TITLE
Mayday Ice Haulers spawning in DX1

### ISSUE THREAD

**Issue by subbob** [DraconisCluster/DX-Issues#11] opened 2024-01-17 02:33 UTC
** tl; dr **
Ice Haulers spawning in high speed zones, thus far only DX1 as far as I know.  

** Full info **
At least one ticket was submitted reporting it. I've seen two tonight.

**Screenshots**
![image](https://github.com/DraconisCluster/DX-Issues/assets/5113030/c7491e9d-0dce-4fcf-ad92-55bf8fab5d86)
GPS:LostIceHauler:-186040.137022504:1607112.53571994:687703.069821816:#FF75C9F1:

**Comment by subbob** [comment] 2024-01-18 02:46
Hangared my station while grinding a ship that had been docked to it.  An Ice Hauler spawned 18km away. Now I am unable to hangar anything and I can't load station from hangar.

![image](https://github.com/DraconisCluster/DX-Issues/assets/5113030/87605d4e-c54a-41ad-a459-d9ef25c5a358)

**Comment by Terif1** [comment] 2024-01-24 03:25
Gonna say this is a duplicate of #3 and we should track there

**Closed as completed by Terif1** 2024-01-24 03:25 UTC
